# This file is generated by C:\enthon\src\scipy-0.3.3_303.4602\setup.py
# It contains system_info results at the time of building this package.
__all__ = ["get_info","show"]

dfftw_info={}
blas_opt_info={'libraries': ['f77blas', 'cblas', 'atlas'], 'library_dirs': ['C:\\ATLAS'], 'language': 'c', 'define_macros': [('ATLAS_INFO', '"\\"3.6.0\\""')]}
atlas_blas_threads_info={}
djbfft_info={}
lapack_opt_info={'libraries': ['lapack', 'f77blas', 'cblas', 'atlas'], 'library_dirs': ['C:\\ATLAS'], 'language': 'f77', 'define_macros': [('ATLAS_INFO', '"\\"3.6.0\\""')]}
x11_info={}
atlas_info={'libraries': ['lapack', 'f77blas', 'cblas', 'atlas'], 'library_dirs': ['C:\\ATLAS'], 'define_macros': [('ATLAS_INFO', '"\\"3.6.0\\""')], 'language': 'f77'}
atlas_threads_info={}
numpy_info={'define_macros': [('NUMERIC_VERSION', '"\\"23.8\\""'), ('NUMERIC', None)], 'include_dirs': ['C:\\Python23\\include']}
fftw_info={}
atlas_blas_info={'libraries': ['f77blas', 'cblas', 'atlas'], 'library_dirs': ['C:\\ATLAS'], 'define_macros': [('ATLAS_INFO', '"\\"3.6.0\\""')], 'language': 'c'}

def get_info(name): g=globals(); return g.get(name,g.get(name+"_info",{}))

def show():
    for name,info_dict in globals().items():
        if name[0]=="_" or type(info_dict) is not type({}): continue
        print name+":"
        if not info_dict:
            print "  NOT AVAILABLE"
        for k,v in info_dict.items():
            v = str(v)
            if k=='sources' and len(v)>200: v = v[:60]+' ...\n... '+v[-60:]
            print '    %s = %s'%(k,v)
        print
    return
    